/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xeon_bsdiff_BsDiffUtil */

#ifndef _Included_com_xeon_bsdiff_BsDiffUtil
#define _Included_com_xeon_bsdiff_BsDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xeon_bsdiff_BsDiffUtil
 * Method:    fileDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xeon_bsdiff_BsDiffUtil_fileDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_xeon_bsdiff_BsDiffUtil
 * Method:    fileCombine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xeon_bsdiff_BsDiffUtil_fileCombine
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
